
#pragma once

/* *************************************************************** *\
 *                         HARDWARE CONFIG                         *
\* *************************************************************** */

#define NB_TANKS 6

#define RGB_STRIP_PIN_SIGNAL 47
#define RGB_STRIP_LEDS_COUNT 120

#define LEVEL_SENSOR_0_PIN 46
#define LEVEL_SENSOR_1_PIN 45
#define LEVEL_SENSOR_2_PIN 44
#define LEVEL_SENSOR_3_PIN 43
#define LEVEL_SENSOR_4_PIN 42
#define LEVEL_SENSOR_5_PIN 41

#define DEBIT_PER_MILLIS 0.1

#define VALVE_0_PIN 38
#define VALVE_1_PIN 37
#define VALVE_2_PIN 36
#define VALVE_3_PIN 35
#define VALVE_4_PIN 34
#define VALVE_5_PIN 33

#define LOAD_CELL_PIN_DATA 32
#define LOAD_CELL_PIN_CLOCK 31
#define LOAD_CELL_CALIBRATION_FACTOR -2170.0    // This value is obtained by using the SparkFun_HX711_Calibration sketch

#define STEPPER_MOTOR_PIN_STEP 40
#define STEPPER_MOTOR_PIN_DIR 39
#define REVOLUTION_STEP 200

#define MIN_PRESSURE 0
#define MAX_PRESSURE 1000

#define SCREEN_WIDTH  480
#define SCREEN_HEIGHT 320

// TFT touchscreen configuration
const int XP = 8, XM = A2, YP = A3, YM = 9;
const int TS_LEFT = 128, TS_RT = 910, TS_TOP = 960, TS_BOT = 93;

/* *************************************************************** *\
 *                            UI CONFIG                            *
\* *************************************************************** */

#define V_SPACING 10
#define H_SPACING 20

/* *************************************************************** *\
 *                            UI COLORS                            *
\* *************************************************************** */

// CM_COLORS_BLACK CM_COLORS_NAVY CM_COLORS_DARKGREEN CM_COLORS_DARKCYAN CM_COLORS_MAROON CM_COLORS_PURPLE
// CM_COLORS_OLIVE CM_COLORS_LIGHTGREY CM_COLORS_DARKGREY CM_COLORS_BLUE CM_COLORS_GREEN CM_COLORS_CYAN
// CM_COLORS_RED CM_COLORS_MAGENTA CM_COLORS_YELLOW CM_COLORS_WHITE CM_COLORS_ORANGE CM_COLORS_GREENYELLOW CM_COLORS_PINK

#define APP_BACKGROUND_COLOR            CM_COLORS_BLACK

#define DEFAULT_OUTLINE_COLOR           CM_COLORS_WHITE
#define DEFAULT_BACKGROUND_COLOR        APP_BACKGROUND_COLOR
#define DEFAULT_TEXT_COLOR              CM_COLORS_WHITE

#define DIALOG_OUTLINE_COLOR            DEFAULT_OUTLINE_COLOR
#define DIALOG_BACKGROUND_COLOR         DEFAULT_BACKGROUND_COLOR

#define START_BUTTON_OUTLINE_COLOR      DEFAULT_OUTLINE_COLOR
#define START_BUTTON_BACKGROUND_COLOR   CM_COLORS_GREEN
#define START_BUTTON_TEXT_COLOR         DEFAULT_TEXT_COLOR

#define STOP_BUTTON_OUTLINE_COLOR       DEFAULT_OUTLINE_COLOR
#define STOP_BUTTON_BACKGROUND_COLOR    CM_COLORS_RED
#define STOP_BUTTON_TEXT_COLOR          DEFAULT_TEXT_COLOR

#define PAGE_TITLE_OUTLINE_COLOR        DEFAULT_OUTLINE_COLOR
#define PAGE_TITLE_BACKGROUND_COLOR     DEFAULT_BACKGROUND_COLOR
#define PAGE_TITLE_TEXT_COLOR           DEFAULT_TEXT_COLOR

#define MENU_PAGE_BUTTON_OUTLINE_COLOR      DEFAULT_OUTLINE_COLOR
#define MENU_PAGE_BUTTON_BACKGROUND_COLOR   DEFAULT_BACKGROUND_COLOR
#define MENU_PAGE_BUTTON_TEXT_COLOR         DEFAULT_TEXT_COLOR

#define SETTINGS_BUTTON_OUTLINE_COLOR       DEFAULT_OUTLINE_COLOR
#define SETTINGS_BUTTON_BACKGROUND_COLOR    DEFAULT_BACKGROUND_COLOR
#define SETTINGS_BUTTON_TEXT_COLOR          DEFAULT_TEXT_COLOR

#define SLIDER_OUTLINE_COLOR            DEFAULT_OUTLINE_COLOR
#define SLIDER_BACKGROUND_COLOR         DEFAULT_BACKGROUND_COLOR
#define SLIDER_FILL_COLOR               CM_COLORS_WHITE
#define SLIDER_LABEL_TEXT_COLOR         CM_COLORS_RED
#define SLIDER_LABEL_BACKGROUND_COLOR   CM_COLORS_CYAN
#define SLIDER_VALUE_TEXT_COLOR         CM_COLORS_CYAN
#define SLIDER_VALUE_BACKGROUND_COLOR   CM_COLORS_RED

#define HENALLUX_LOGO_COLOR     CM_COLORS_NAVY
#define ISICLAMP_LOGO_COLOR     CM_COLORS_WHITE
